### PR TITLE
fix(frontend/settings): change theme tool button position

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Changes position of overlay button in settings

**Before**
image

**After**
image

### Time spent on PR
2 mins

### Related
https://github.com/ShabadOS/desktop/pull/583#issuecomment-651404400

### Reviewers
@bhajneet @Harjot1Singh

### CODE REVIEW

**Comment by bhajneet** [comment]
This should not have been opened for review with such a noticeable style issue.

image

**Comment by bhajneet** [comment]
Possibly related to https://github.com/ShabadOS/desktop/issues/519

**Comment by saihaj** [comment]
@Harjot1Singh should I address #519 in new PR or do it here? @bhajneet is the button layout change acceptable though?

**Comment by Harjot1Singh** [comment]
It might actually make more sense to do #519 first if it won’t take too long, and merge it in

**Comment by saihaj** [comment]
@bhajneet MaterialUI Grid and Button have some sort of padding is causing the green lines as shown in your screenshot. 

image

**Comment by bhajneet** [comment]
Can you add a css rule for sibling of button to remove it's top padding?

**Comment by saihaj** [comment]
Removing top padding doesn't help. I also tried margin but that didn't work.
image

That yellow region is the one that needs to be removed somehow.

image

**Comment by bhajneet** [comment]
Yeah, so that would be top margin then. Rule would be similar to 

```
.MuiButtonbase-root + .MuiButtonbase-root {
  margin-top: 0;
}
```

**Comment by Harjot1Singh** [comment]
What is happening with this PR @saihaj?

**Comment by saihaj** [comment]
I think me and @bhajneet were trying to do something and that didn’t work. Can you please run it locally and see. I think this is what the issue is https://github.com/ShabadOS/presenter/pull/586#issuecomment-653923315

**Comment by bhajneet** [comment]
Too stale

**Pull request closed without merging**
